### ISSUE TITLE
week 3:  two exercise folders or three?

### ISSUE THREAD

**Issue by nbogie** [CodeYourFuture/JavaScript-Core-1-Coursework-Week3#1]
The readme states: 

"The exercises are split into two folders: mandatory and extra"

but there are actually *three* folders:
1-exercises, 2-mandatory, and 3-extra

https://github.com/CodeYourFuture/JavaScript-Core-1-Coursework-Week3

**Comment by ChrisOwen101** [comment]
@nbogie - Fixed, thanks for raising
