### ISSUE TITLE
8-password validator 

### ISSUE THREAD

**Issue by ahmedkortas** [CodeYourFuture/JavaScript-Core-1-Coursework-Week3#111]
test("Example 2", () => {
  expect(
    validatePasswords([
      "StUFf27%",
      "Pl3nty!",
      "Jai33",
      "shajsaUA**&&",
      "Pl3nty!",
    ])
  ).toEqual([true, true, false, false, false]);// the last value should be = true 
});

**Comment by ChrisOwen101** [comment]
@ahmedkortas - The test is correct because of this requirement in the brief

> Passwords must not be any previous password in the passwords array. 

Does this solve your problem?

**Comment by ahmedkortas** [comment]
great thank you
